# Generated by Django 2.2 on 2019-04-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='hnnews_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newslinks',
            name='title_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
