# Generated by Django 2.2 on 2019-04-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0002_auto_20190412_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslinks',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
