# Generated by Django 2.2 on 2019-04-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0002_newslinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslinks',
            name='title_link',
            field=models.URLField(max_length=400),
        ),
    ]
