# Generated by Django 2.2 on 2019-04-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0003_auto_20190412_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslinks',
            name='karma_points',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
