# Generated by Django 2.2 on 2019-04-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslinks',
            name='time_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
