# Generated by Django 2.2 on 2019-04-10 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0006_newslinks_time_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslinks',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
