# Generated by Django 2.2 on 2019-04-10 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0007_auto_20190410_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslinks',
            name='downvotes',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='newslinks',
            name='karma_points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='newslinks',
            name='num_comments',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='newslinks',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newslinks',
            name='upvotes',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
