# Generated by Django 2.2 on 2019-04-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0008_auto_20190410_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslinks',
            name='karma_points',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
