# Generated by Django 2.2 on 2019-04-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0009_auto_20190410_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslinks',
            name='downvotes',
        ),
    ]
