# Generated by Django 2.2 on 2019-04-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0010_remove_newslinks_downvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslinks',
            name='downvotes',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
