# Generated by Django 2.2 on 2019-04-17 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0013_auto_20190417_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvotescomment',
            old_name='upvote_count',
            new_name='comment_voted',
        ),
        migrations.RemoveField(
            model_name='upvotesnewslink',
            name='upvote_count',
        ),
        migrations.AddField(
            model_name='upvotesnewslink',
            name='newslink_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackernews.Comments'),
        ),
        migrations.AlterField(
            model_name='upvotescomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackernews.Comments'),
        ),
    ]
